# Generated by Django 2.2.4 on 2019-08-30 07:49

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModels',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=20, verbose_name='类型名')),
                ('author_extend', models.CharField(max_length=150, null=True, verbose_name='扩展字段')),
                ('author_state', models.IntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='LabelModels',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=20, verbose_name='类型名')),
                ('label_extend', models.CharField(max_length=150, null=True, verbose_name='扩展字段')),
                ('label_state', models.IntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'label',
            },
        ),
        migrations.CreateModel(
            name='LearnTypeModels',
            fields=[
                ('learn_id', models.AutoField(primary_key=True, serialize=False)),
                ('learn_name', models.CharField(max_length=20, verbose_name='类型名')),
                ('learn_extend', models.CharField(max_length=150, null=True, verbose_name='扩展字段')),
                ('learn_state', models.IntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学习类型',
                'verbose_name_plural': '学习类型',
                'db_table': 'learn',
            },
        ),
        migrations.CreateModel(
            name='GraphicRecordModels',
            fields=[
                ('graphic_id', models.AutoField(primary_key=True, serialize=False)),
                ('graphic_title', models.CharField(max_length=150, verbose_name='标题')),
                ('graphic_body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('graphic_state', models.IntegerField(default=1, verbose_name='状态')),
                ('graphic_views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('graphic_cover', models.ImageField(max_length=255, upload_to='images', verbose_name='封面')),
                ('graphic_about', models.CharField(max_length=100, verbose_name='简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('graphic_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myblog.AuthorModels', verbose_name='作者')),
                ('graphic_learn', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myblog.LearnTypeModels', verbose_name='分类')),
            ],
            options={
                'verbose_name': '图文',
                'verbose_name_plural': '图文',
                'db_table': 'graphic',
            },
        ),
        migrations.CreateModel(
            name='ArticleRecordModels',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=150, verbose_name='标题')),
                ('article_body', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('article_state', models.IntegerField(default=1, verbose_name='状态')),
                ('article_views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('article_cover', models.ImageField(max_length=255, upload_to='images', verbose_name='封面')),
                ('article_about', models.CharField(max_length=100, verbose_name='简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('article_author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myblog.AuthorModels', verbose_name='作者')),
                ('article_learn', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myblog.LearnTypeModels', verbose_name='分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'article',
            },
        ),
    ]
