# Generated by Django 2.2.4 on 2019-09-12 07:24

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import system.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, verbose_name='标题')),
                ('cover', models.ImageField(max_length=256, storage=system.storage.ImageStorage(), upload_to='images/%Y/%m/%d', verbose_name='封面图')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('state', models.BooleanField(choices=[(True, '正常'), (False, '异常')], default=True, verbose_name='状态')),
                ('author', models.IntegerField(default=1, verbose_name='作者')),
                ('views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('collection', models.IntegerField(default=0, verbose_name='收藏量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='FriendsModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('friend_name', models.CharField(max_length=50, unique=True, verbose_name='网站名称')),
                ('friend_url', models.URLField(blank=True, max_length=256, null=True, verbose_name='网站链接')),
                ('state', models.BooleanField(choices=[(True, '正常'), (False, '异常')], default=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'db_table': 'friend',
            },
        ),
        migrations.CreateModel(
            name='SourceModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='来源名称')),
                ('state', models.BooleanField(choices=[(True, '正常'), (False, '异常')], default=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '来源',
                'verbose_name_plural': '来源',
                'db_table': 'source',
            },
        ),
        migrations.CreateModel(
            name='TagsModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='标签名')),
                ('state', models.BooleanField(choices=[(True, '正常'), (False, '异常')], default=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='TypeModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='类型名称')),
                ('state', models.BooleanField(choices=[(True, '正常'), (False, '异常')], default=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型',
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='RecommendModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(choices=[(True, '正常'), (False, '异常')], default=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myblog.BlogModels', verbose_name='博客ID')),
            ],
            options={
                'verbose_name': '站长推荐',
                'verbose_name_plural': '站长推荐',
                'db_table': 'recommend',
            },
        ),
        migrations.AddField(
            model_name='blogmodels',
            name='blog_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myblog.TypeModels', verbose_name='博客分类'),
        ),
        migrations.AddField(
            model_name='blogmodels',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myblog.SourceModels', verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='blogmodels',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_blog', to='myblog.TagsModels', verbose_name='博客标签'),
        ),
    ]
