# Generated by Django 2.2.4 on 2019-09-03 08:26

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphicrecordmodels',
            name='graphic_cover',
            field=models.ImageField(max_length=255, storage=system.storage.ImageStorage(), upload_to='images/%Y/%m/%d', verbose_name='封面'),
        ),
    ]
