# Generated by Django 2.2.4 on 2019-09-03 08:31

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20190903_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerecordmodels',
            name='article_cover',
            field=models.ImageField(max_length=255, storage=system.storage.ImageStorage(), upload_to='images/%Y/%m/%d', verbose_name='封面'),
        ),
    ]
