# Generated by Django 2.2.4 on 2019-09-09 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190903_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendModels',
            fields=[
                ('recommend_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommend_title', models.CharField(max_length=150, verbose_name='标题')),
                ('recommend_state', models.IntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recommend_graphic_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='myblog.GraphicRecordModels', verbose_name='图文博客ID')),
            ],
            options={
                'verbose_name': '站长推荐',
                'verbose_name_plural': '站长推荐',
                'db_table': 'recommends',
            },
        ),
    ]
