# Generated by Django 2.2.4 on 2019-09-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_recommendmodels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendmodels',
            name='recommend_graphic_id',
            field=models.IntegerField(default=1, verbose_name='图文博客ID'),
        ),
    ]
